name: Dependabot

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dependabot:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write

    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == '${{ github.repository_owner }}/${{ github.repository_name }}'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add labels for Dependabot PRs
        run: gh pr edit "$PR_URL" --add-label "dependencies,automated,security"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}

      - name: Add production dependency label
        if: steps.metadata.outputs.dependency-type == 'direct:production'
        run: gh pr edit "$PR_URL" --add-label "production"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}

      - name: Add development dependency label
        if: steps.metadata.outputs.dependency-type == 'direct:development'
        run: gh pr edit "$PR_URL" --add-label "development"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
